 
services:
  dns:
    build: 
      context: ./DNS
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"

  proxy:
    build: 
      context: ./Proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - mail
    networks:
      - asa-network

  mail:
    build: 
      context: ./Mail
      dockerfile: Dockerfile
    container_name: mail
    ports:
      - "25:25/tcp"   # SEMP
      - "587:587/tcp" # SMP Client
      - "110:110/tcp" # POP3
      - "143:143/tcp" # IMAP
    networks:
      - asa-network


  roundcubedb:
    image: mysql:latest
    container_name: roundcubedb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail
    networks:
      - asa-network

  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - roundcube:/var/www/html
    ports:
      - 9001:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=gilson.asa.br
      - ROUNDCUBEMAIL_SMTP_SERVER=mail.gilson.asa.br
    networks:
      - asa-network

volumes:
  mail:
  roundcube:
  db:

#Docker Networks
networks:
  asa-network:
    driver: bridge