 
services:
  dns:
    build: 
      context: ./DNS
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
    # Ver onde caralhos esses arquivos vão
    volumes:
      - ./Webmail/bind/db.praia.com
      - ./Webmail/bind/named.conf.local

  proxy:
    build: 
      context: ./Proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - mail
    networks:
      - asa-network

  mail:
    build: 
      context: ./Mail
      dockerfile: Dockerfile
    container_name: mail
    ports:
      - "25:25/tcp"   # SEMP
      - "587:587/tcp" # SMP Client
      - "110:110/tcp" # POP3
      - "143:143/tcp" # IMAP
    networks:
      - asa-network
    # Mesma coisa, ajeitar local do volume
    volumes:
      - ./Mail/10-auth.conf
      - ./Mail/main.cf

  webmail:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    networks:
      - asa-network
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://email:143
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://email:25
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
    depends_on:
      - email
    volumes:
      - ./Webmail/Config/config.inc.php:/var/roundcube/config/config.inc.php
#      - ./Containers/MAIL/Config/ssl/email.crt:/etc/ssl/certs/email.crt:ro

#Docker Networks
networks:
  asa-network:
    driver: bridge