 
services:
  dns:
    build: 
      context: ./DNS
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
    volumes:
      - ./DNS/bind/db.areia.branca.com:/etc/bind/db.areia.branca.com
      - ./DNS/bind/named.conf.local:/etc/bind/named.conf.local
    networks:
      - main-network

  mail:
    build: 
      context: ./Mail
      dockerfile: Dockerfile
    container_name: mail
    ports:
      - "25:25/tcp"   # SEMP
      - "587:587/tcp" # SMP Client
      - "110:110/tcp" # POP3
      - "143:143/tcp" # IMAP
      - "465:465/tcp"
    networks:
      - main-network
    volumes:
      - ./Mail/config/main.cf:/etc/postfix/main.cf
      - ./Mail/config/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./Mail/config/10-master.conf:/etc/dovecot/conf.d/10-master.conf
      - ./Mail/config/10-auth.conf:/etc/dovecot/conf.d/10-auth.conf
      - ./Mail/config/master.conf:/etc/postfix/master.cf

  proxy:
    build: 
      context: ./Proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mail
    networks:
      - main-network
    volumes:
      - ./Proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./Proxy/nginx.conf:/etc/nginx/nginx.conf
  

  roundcubedb:
    image: mysql:latest
    container_name: roundcubedb
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail
    networks:
      - main-network

  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    depends_on:
      - roundcubedb
      - dns
    links:
      - roundcubedb
    volumes:
      - roundcube:/var/www/html
    ports:
      - "8080:80"
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=mail.areia.branca.com
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://mail.areia.branca.com
      - ROUNDCUBEMAIL_SMTP_PORT=465
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
    networks:
      - main-network
    dns:
      10.25.2.79

  ssh:
    build:
      context: ./SSH
      dockerfile: Dockerfile
    image: ssh
    container_name: ssh
    ports:
      - "22:22"
    networks:
      - main-network

volumes:
  mail:
  roundcube:
  db:

networks:
  main-network:
    driver: bridge