 
services:
  dns:
    build: 
      context: ./DNS
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
    volumes:
      - ./DNS/bind/db.areia.branca.com:/etc/bind/db.areia.branca.com
      - ./DNS/bind/named.conf.local:/etc/bind/named.conf.local

  proxy:
    build: 
      context: ./Proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - mail
    networks:
      - asa-network

  mail:
    build: 
      context: ./Mail
      dockerfile: Dockerfile
    container_name: mail
    ports:
      - "25:25/tcp"   # SEMP
      - "587:587/tcp" # SMP Client
      - "110:110/tcp" # POP3
      - "143:143/tcp" # IMAP
    networks:
      - asa-network
    volumes:
      - ./Mail/config/main.cf:/etc/postfix/main.cf
      - ./Mail/config/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./Mail/config/10-master.conf:/etc/dovecot/conf.d/10-master.conf

  webmail:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    networks:
      - asa-network
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://email:143
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://email:25
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
    depends_on:
      - mail
    volumes:
      - ./Webmail/config/config.inc.php:/var/roundcube/config/config.inc.php

#Docker Networks
networks:
  asa-network:
    driver: bridge