services:    
  db-client2:
    image: mariadb:latest
    container_name: db-client2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    networks:
      - main-network
    volumes:
      - db_data:/var/lib/mysql
      
  wordpress-client2:
    image: wordpress:latest
    container_name: wordpress-client2
    depends_on:
      - db
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: db-client2
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - main-network
      - external-network
    volumes:
      - wordpress_data:/var/www/html

  wordpress-2-client2:
    image: wordpress:latest
    container_name: wordpress-2
    depends_on:
      - db
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: db-client2
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - main-network
      - external-network
    volumes:
      - wordpress_data:/var/www/html

  ssh:
    build:
      context: ./SSH
      dockerfile: Dockerfile
    image: ssh
    container_name: ssh-client2
    ports:
      - "2223:22"
    networks:
      - main-network

volumes:
  db_data:
  wordpress_data:


networks:
  main-network:
    driver: bridge
  external-network:
    external: true